((nil .
      ((cider-clojure-cli-aliases . "-A:test")
       (cider-default-cljs-repl . shadow)
       (cider-shadow-default-options . "app")
       (cider-offer-to-open-cljs-app-in-browser . nil)
       (clojure-indent-style . 'align-arguments)
       (eval . (define-clojure-indent
		 (ns '(1 (0)))
		 (cond-> 0)
		 (cond->> 0)
		 (as-> 0)
		 (reg-event-fx 0)
		 (reg-sub 0)
		 (defroutes 'defun)
		 (GET 2)
		 (POST 2)
		 (PUT 2)
		 (DELETE 2)
		 (HEAD 2)
		 (ANY 2)
		 (OPTIONS 2)
		 (PATCH 2)
		 (rfn 2)
		 (let-routes 1)
		 (context 2))))))
