apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: hs
        imagePullPolicy: Never
        ports:
         - containerPort: 3000
        env:
          # Use secret in real usage
        - name: DBNAME
          value: hs
        - name: DBHOST
          value: postgres